background {
    monitor =
    path = $HOME/.config/Wallpapers/Hyprlock4
    color = rgba(071b16ff)
    blur_passes = 0
}

# The Hour (Top)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
    color = rgba(d1e8e2ff)
    font_size = 120
    font_family = Noto Sans Display SemiCondensed Bold
    position = 0, 180
    halign = center
    valign = center
}

# The Minutes
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = rgba(d1e8e2ff)
    font_size = 120
    font_family = Noto Sans Display SemiCondensed Bold
    position = 0, 40
    halign = center
    valign = center
}

# Day of the week
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A")"
    color = rgba(d1e8e2ee)
    font_size = 14
    font_family = Noto Sans Display SemiCondensed
    position = 0, -40
    halign = center
    valign = center
}

# Date (Day and Month)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%d %b")"
    color = rgba(d1e8e2bb)
    font_size = 10
    font_family = Noto Sans Display SemiCondensed
    position = 0, -60
    halign = center
    valign = center
}

# Input field
input-field {
    monitor =
    size = 150, 30
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(d1e8e233)
    inner_color = rgba(071b1666)
    font_color = rgba(d1e8e2ff)
    fade_on_empty = true
    placeholder_text =
    hide_input = false
    position = 0, -150
    halign = center
    valign = center
}
